import { Request, Response } from 'express';
import bcrypt from 'bcryptjs';
import { z } from 'zod';
import prisma from '../prisma';
import { generateFellowshipNumber } from '../utils/fellowshipNumberGenerator';

const createMemberSchema = z.object({
    fullName: z.string().min(1),
    email: z.string().email(),
    phoneNumber: z.string(),
    gender: z.enum(['MALE', 'FEMALE']),
    residence: z.string().optional(),
    course: z.string().optional(),
    yearOfStudy: z.number().min(1).max(7).optional(),
});

// Create new member
export const createMember = async (req: Request, res: Response) => {
    try {
        const validatedData = createMemberSchema.parse(req.body);

        // Check if email already exists
        const existingMember = await prisma.member.findUnique({
            where: { email: validatedData.email },
        });

        if (existingMember) {
            return res.status(400).json({ error: 'Email already registered' });
        }

        // Generate fellowship number using existing utility
        const fellowshipNumber = await generateFellowshipNumber();

        // Hash the fellowship number to use as default password
        const hashedPassword = await bcrypt.hash(fellowshipNumber, 10);

        // Create member (qrCode is auto-generated by default(uuid()))
        const member = await prisma.member.create({
            data: {
                fullName: validatedData.fullName,
                email: validatedData.email,
                phoneNumber: validatedData.phoneNumber,
                gender: validatedData.gender,
                residence: validatedData.residence,
                course: validatedData.course,
                yearOfStudy: validatedData.yearOfStudy,
                fellowshipNumber,
                password: hashedPassword,
                role: 'MEMBER',
            },
            select: {
                id: true,
                fullName: true,
                email: true,
                fellowshipNumber: true,
                qrCode: true,
                phoneNumber: true,
                gender: true,
                residence: true,
                course: true,
                yearOfStudy: true,
                role: true,
                createdAt: true,
            },
        });

        res.status(201).json(member);
    } catch (error) {
        if (error instanceof z.ZodError) {
            return res.status(400).json({ error: 'Invalid data', details: error.issues });
        }
        console.error('Error creating member:', error);
        res.status(500).json({ error: 'Failed to create member' });
    }
};

// Get all members (with optional search)
export const getMembers = async (req: Request, res: Response) => {
    try {
        const { search } = req.query;

        const where = search
            ? {
                OR: [
                    { fullName: { contains: search as string, mode: 'insensitive' as const } },
                    { email: { contains: search as string, mode: 'insensitive' as const } },
                    { fellowshipNumber: { contains: search as string, mode: 'insensitive' as const } },
                ],
            }
            : {};

        const members = await prisma.member.findMany({
            where,
            select: {
                id: true,
                fullName: true,
                email: true,
                fellowshipNumber: true,
                phoneNumber: true,
                role: true,
            },
            orderBy: {
                fullName: 'asc',
            },
            take: 20, // Limit results
        });

        res.json(members);
    } catch (error) {
        console.error('Error fetching members:', error);
        res.status(500).json({ error: 'Failed to fetch members' });
    }
};
